version: '3'

services:
  db:
    restart: always
    image: postgres
    env_file:
      - ./env/postgresql.env
    volumes:
      - db-data:/var/lib/postgresql
    depends_on:
      - backup

  backup:
    restart: always
    image: postgres
    volumes:
      - db-data:/var/lib/backup/data
    command: "true"

  nginx:
    restart: always
    build: ./nginx
    image: mynginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/:/www/ssl/:ro
      - ./mysite/static/:/www/static/:ro
      - /var/log/nginx
    depends_on:
      - webapps

  webapps:
    restart: always
    build: ./mysite
    image: mysite-django
    expose:
      - "8000"
    env_file:
      - ./env/webapps.env
    volumes:
      - ./mysite:/webapps
    depends_on:
      - db
      - redis-server
    command: /bin/bash run_webapps.sh

  redis-server:
    restart: always
    image: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis

  celery:
    restart: always
    build: ./mysite
    image: mysite-django
    env_file:
      - ./env/webapps.env
    depends_on:
      - redis-server
      - webapps
    command: /bin/bash run_celery.sh

volumes:
  db-data:
  redis-data:
